export const STATION_PRICE_KEY_TO_FUEL_ID: Record<string, string> = {
  'Precio Gasolina 95 E5': '1',
  'Precio Gasolina 98 E5': '3',
  'Precio Gasoleo A': '4',
  'Precio Gasoleo Premium': '5',
  'Precio Gasoleo B': '6',
  'Precio Biodiesel': '8',
  'Precio Bioetanol': '16',
  'Precio Gases licuados del petróleo': '17',
  'Precio Gas Natural Comprimido': '18',
  'Precio Gas Natural Licuado': '19',
  'Precio Gasolina 95 E5 Premium': '20',
  'Precio Gasolina 98 E10': '21',
  'Precio Hidrogeno': '22',
  'Precio Gasolina 95 E10': '23',
  'Precio Gasolina 95 E25': '24',
  'Precio Gasolina 95 E85': '25',
  'Precio Adblue': '26',
  'Precio Diésel Renovable': '27',
  'Precio Gasolina Renovable': '28',
  'Precio Metanol': '29',
  'Precio Amoniaco': '30',
  'Precio Biogas Natural Comprimido': '31',
  'Precio Biogas Natural Licuado': '32',
};
